# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Testgoogleclass():
  def setup_method(self, method):
    self.driver = webdriver.Ie()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_google_func(self):
    self.driver.get("https://www.google.com/")
    self.driver.set_window_size(952, 820)
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("老干妈")
    self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("老干妈666")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
  
